"""legacy snapshots

Revision ID: 44cbb5c5e7e9
Revises: 6c0e8bbc5a30
Create Date: 2026-09-16 12:29:20.469041
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '44cbb5c5e7e9'
down_revision: Union[str, Sequence[str], None] = '6c0e8bbc5a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_legados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('codigo_pedido', sa.String(length=80), nullable=False),
    sa.Column('codigo_servico', sa.String(length=80), nullable=True),
    sa.Column('pedido_id', sa.Uuid(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('normalized_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_importados.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'row_number', name='uq_registro_legado_linha')
    )
    op.create_index(op.f('ix_registros_legados_codigo_pedido'), 'registros_legados', ['codigo_pedido'], unique=False)
    op.create_index(op.f('ix_registros_legados_documento_id'), 'registros_legados', ['documento_id'], unique=False)
    op.create_index(op.f('ix_registros_legados_pedido_id'), 'registros_legados', ['pedido_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_legados_pedido_id'), table_name='registros_legados')
    op.drop_index(op.f('ix_registros_legados_documento_id'), table_name='registros_legados')
    op.drop_index(op.f('ix_registros_legados_codigo_pedido'), table_name='registros_legados')
    op.drop_table('registros_legados')
    # ### end Alembic commands ###
