"""initial schema

Revision ID: 6c0e8bbc5a30
Revises:
Create Date: 2026-09-16 12:22:44.862946
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '6c0e8bbc5a30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('maquinas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('capacidades_producao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('process', sa.String(length=50), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('limit', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('machine_id', sa.Uuid(), nullable=True),
    sa.Column('shift', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['maquinas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', 'process', 'metric', 'machine_id', 'shift', name='uq_capacidade')
    )
    op.create_index(op.f('ix_capacidades_producao_day'), 'capacidades_producao', ['day'], unique=False)
    op.create_table('lotes_importacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=80), nullable=False),
    sa.Column('codigo_interno_normalizado', sa.String(length=80), nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=True),
    sa.Column('carrinho', sa.String(length=80), nullable=True),
    sa.Column('codigo_cliente_pdf', sa.String(length=80), nullable=True),
    sa.Column('cliente_pdf', sa.String(length=255), nullable=True),
    sa.Column('cliente_documento', sa.String(length=30), nullable=True),
    sa.Column('cliente_contato', sa.String(length=120), nullable=True),
    sa.Column('vendedor_pdf', sa.String(length=180), nullable=True),
    sa.Column('loja_venda', sa.String(length=120), nullable=True),
    sa.Column('tipo_ordem_venda', sa.String(length=120), nullable=True),
    sa.Column('modalidade', sa.String(length=80), nullable=True),
    sa.Column('remessa', sa.String(length=80), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('bairro', sa.String(length=160), nullable=True),
    sa.Column('cidade', sa.String(length=160), nullable=True),
    sa.Column('cep', sa.String(length=30), nullable=True),
    sa.Column('peso', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('valor_produtos', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('taxa_entrega', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('condicao_pagamento', sa.String(length=255), nullable=True),
    sa.Column('informacao_separacao_pdf', sa.Text(), nullable=True),
    sa.Column('observacao_pdf', sa.Text(), nullable=True),
    sa.Column('data_carregamento', sa.Date(), nullable=True),
    sa.Column('previsao_entrega', sa.Date(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=False),
    sa.Column('status_dados', sa.String(length=40), nullable=False),
    sa.Column('status_producao', sa.String(length=40), nullable=False),
    sa.Column('observacao_operacional', sa.Text(), nullable=True),
    sa.Column('falta_material', sa.Boolean(), nullable=False),
    sa.Column('programado_em', sa.Date(), nullable=True),
    sa.Column('turno', sa.String(length=80), nullable=True),
    sa.Column('maquina_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_index(op.f('ix_pedidos_carrinho'), 'pedidos', ['carrinho'], unique=False)
    op.create_index(op.f('ix_pedidos_cidade'), 'pedidos', ['cidade'], unique=False)
    op.create_index(op.f('ix_pedidos_cliente_documento'), 'pedidos', ['cliente_documento'], unique=False)
    op.create_index(op.f('ix_pedidos_cliente_pdf'), 'pedidos', ['cliente_pdf'], unique=False)
    op.create_index(op.f('ix_pedidos_codigo_interno_normalizado'), 'pedidos', ['codigo_interno_normalizado'], unique=True)
    op.create_index('ix_pedidos_criado', 'pedidos', ['created_at'], unique=False)
    op.create_index(op.f('ix_pedidos_data_carregamento'), 'pedidos', ['data_carregamento'], unique=False)
    op.create_index(op.f('ix_pedidos_previsao_entrega'), 'pedidos', ['previsao_entrega'], unique=False)
    op.create_index(op.f('ix_pedidos_programado_em'), 'pedidos', ['programado_em'], unique=False)
    op.create_index(op.f('ix_pedidos_status_dados'), 'pedidos', ['status_dados'], unique=False)
    op.create_index(op.f('ix_pedidos_status_producao'), 'pedidos', ['status_producao'], unique=False)
    op.create_table('documentos_importados',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('pedido_id', sa.Uuid(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=40), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('data_importacao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario_importacao', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('quantidade_registros', sa.Integer(), nullable=False),
    sa.Column('quantidade_criados', sa.Integer(), nullable=False),
    sa.Column('quantidade_atualizados', sa.Integer(), nullable=False),
    sa.Column('quantidade_ignorados', sa.Integer(), nullable=False),
    sa.Column('quantidade_erros', sa.Integer(), nullable=False),
    sa.Column('original_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['lotes_importacao.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_importacao'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_importados_hash_sha256'), 'documentos_importados', ['hash_sha256'], unique=True)
    op.create_index(op.f('ix_documentos_importados_pedido_id'), 'documentos_importados', ['pedido_id'], unique=False)
    op.create_table('eventos_producao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('machine_id', sa.Uuid(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['maquinas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_producao_pedido_id'), 'eventos_producao', ['pedido_id'], unique=False)
    op.create_table('historico_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_status', sa.String(length=40), nullable=True),
    sa.Column('new_status', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historico_status_pedido_id'), 'historico_status', ['pedido_id'], unique=False)
    op.create_table('observacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observacoes_pedido_id'), 'observacoes', ['pedido_id'], unique=False)
    op.create_table('servicos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_servico', sa.String(length=80), nullable=False),
    sa.Column('codigo_servico_normalizado', sa.String(length=80), nullable=False),
    sa.Column('cliente_origem', sa.String(length=255), nullable=True),
    sa.Column('cliente_final_origem', sa.String(length=255), nullable=True),
    sa.Column('vendedor_origem', sa.String(length=180), nullable=True),
    sa.Column('enviado_producao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('central', sa.String(length=120), nullable=True),
    sa.Column('linha_producao', sa.String(length=180), nullable=True),
    sa.Column('chapas', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('cortes', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('metros_lineares_corte', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('pecas', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('fita_aplicada', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('usinagens', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('corte_realizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fitagem_realizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usinagem_realizada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('previsao_entrega', sa.Date(), nullable=True),
    sa.Column('observacao_origem', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id', 'codigo_servico_normalizado', name='uq_servico_pedido_codigo')
    )
    op.create_index(op.f('ix_servicos_codigo_servico_normalizado'), 'servicos', ['codigo_servico_normalizado'], unique=False)
    op.create_index(op.f('ix_servicos_pedido_id'), 'servicos', ['pedido_id'], unique=False)
    op.create_table('auditoria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documentos_importados.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_at'), 'auditoria', ['at'], unique=False)
    op.create_index(op.f('ix_auditoria_entity_id'), 'auditoria', ['entity_id'], unique=False)
    op.create_table('erros_importacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('linha', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_importados.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pedido_id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('numero_item', sa.String(length=30), nullable=False),
    sa.Column('codigo_produto', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('ncm', sa.String(length=30), nullable=True),
    sa.Column('peso', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('tipo_item', sa.String(length=40), nullable=False),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_importados.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id', 'numero_item', 'codigo_produto', name='uq_item_documento_num_codigo')
    )
    op.create_index(op.f('ix_itens_pedido_documento_id'), 'itens_pedido', ['documento_id'], unique=False)
    op.create_index(op.f('ix_itens_pedido_pedido_id'), 'itens_pedido', ['pedido_id'], unique=False)
    op.create_table('pendencias_vinculacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('documento_id', sa.Uuid(), nullable=False),
    sa.Column('pedido_pdf', sa.String(length=80), nullable=True),
    sa.Column('cliente_pdf', sa.String(length=255), nullable=True),
    sa.Column('carrinho', sa.String(length=80), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_importados.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento_id')
    )
    op.create_index(op.f('ix_pendencias_vinculacao_pedido_pdf'), 'pendencias_vinculacao', ['pedido_pdf'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pendencias_vinculacao_pedido_pdf'), table_name='pendencias_vinculacao')
    op.drop_table('pendencias_vinculacao')
    op.drop_index(op.f('ix_itens_pedido_pedido_id'), table_name='itens_pedido')
    op.drop_index(op.f('ix_itens_pedido_documento_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_table('erros_importacao')
    op.drop_index(op.f('ix_auditoria_entity_id'), table_name='auditoria')
    op.drop_index(op.f('ix_auditoria_at'), table_name='auditoria')
    op.drop_table('auditoria')
    op.drop_index(op.f('ix_servicos_pedido_id'), table_name='servicos')
    op.drop_index(op.f('ix_servicos_codigo_servico_normalizado'), table_name='servicos')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_observacoes_pedido_id'), table_name='observacoes')
    op.drop_table('observacoes')
    op.drop_index(op.f('ix_historico_status_pedido_id'), table_name='historico_status')
    op.drop_table('historico_status')
    op.drop_index(op.f('ix_eventos_producao_pedido_id'), table_name='eventos_producao')
    op.drop_table('eventos_producao')
    op.drop_index(op.f('ix_documentos_importados_pedido_id'), table_name='documentos_importados')
    op.drop_index(op.f('ix_documentos_importados_hash_sha256'), table_name='documentos_importados')
    op.drop_table('documentos_importados')
    op.drop_index(op.f('ix_pedidos_status_producao'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_status_dados'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_programado_em'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_previsao_entrega'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_data_carregamento'), table_name='pedidos')
    op.drop_index('ix_pedidos_criado', table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_codigo_interno_normalizado'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_cliente_pdf'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_cliente_documento'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_cidade'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_carrinho'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_table('lotes_importacao')
    op.drop_index(op.f('ix_capacidades_producao_day'), table_name='capacidades_producao')
    op.drop_table('capacidades_producao')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('maquinas')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
