"""Defaults which administrators may subsequently change in the database."""

ROLES = ("ADMIN", "GESTOR", "PLANEJAMENTO", "OPERADOR", "CONSULTA")
DATA_STATUSES = (
    "AGUARDANDO_CARRINHO", "DADOS_PARCIAIS", "DADOS_COMPLETOS",
    "PENDENCIA_VINCULACAO", "ERRO_IMPORTACAO",
)
PRODUCTION_STATUSES = (
    "AGUARDANDO_DADOS", "AGUARDANDO_PROGRAMACAO", "PROGRAMADO",
    "AGUARDANDO_MATERIAL", "LIBERADO_PRODUCAO", "EM_CORTE",
    "AGUARDANDO_FITAGEM", "EM_FITAGEM", "AGUARDANDO_USINAGEM",
    "EM_USINAGEM", "PRODUCAO_FINALIZADA", "AGUARDANDO_CARREGAMENTO",
    "LIBERADO_CARREGAMENTO", "ENTREGUE", "RETIRADO", "CANCELADO",
)
PRIORITIES = ("BAIXA", "NORMAL", "ALTA", "URGENTE")
PROCESS_EVENTS = {
    "INICIAR_CORTE": "EM_CORTE",
    "FINALIZAR_CORTE": "AGUARDANDO_FITAGEM",
    "INICIAR_FITAGEM": "EM_FITAGEM",
    "FINALIZAR_FITAGEM": "AGUARDANDO_USINAGEM",
    "INICIAR_USINAGEM": "EM_USINAGEM",
    "FINALIZAR_PRODUCAO": "PRODUCAO_FINALIZADA",
}
PERMISSIONS = {
    "import": {"ADMIN", "GESTOR"},
    "reprocess": {"ADMIN"},
    "link": {"ADMIN", "GESTOR"},
    "plan": {"ADMIN", "GESTOR", "PLANEJAMENTO"},
    "produce": {"ADMIN", "GESTOR", "OPERADOR"},
    "material": {"ADMIN", "GESTOR", "OPERADOR"},
    "admin": {"ADMIN"},
}
